
#define TAPPING_TERM 200
#define RETRO_TAPPING
#define HOLD_ON_OTHER_KEY_PRESS

#define AUTO_SHIFT_TIMEOUT 170
#define AUTO_SHIFT_DISABLED_AT_STARTUP

#define LEADER_TIMEOUT 800
#define LEADER_PER_KEY_TIMING
